version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1212
      MYSQL_DATABASE: bancoteste01
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1212"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      # MUITO IMPORTANTE: O IntelliJ usará a porta 3356 para se conectar
      - "3356:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge