# Configurações do banco de dados
spring.datasource.url=jdbc:mysql://localhost:3356/bancoteste01?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC


# Configurações de autenticação do banco de dados
spring.datasource.username=root

# Configurações de autenticação do banco de dados
spring.datasource.password=1212

# Configurações do JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update

# Configurações de exibição de SQL no console
spring.jpa.show-sql=true


# Configurações do driver JDBC para MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações de pool de conexões HikariCP
spring.datasource.hikari.initialization-fail-timeout=30000

# Configurações de dialeto do Hibernate para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configurações de dialeto do Hibernate para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect